language: node_js

node_js:
  - 'node'

cache:
  directories:
    - 'node_modules'
script:
  - yarn test
  - yarn production

deploy:
  provider: npm
  email: ragoga48@gmail.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
